name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag version
        run: echo "IMAGE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Write version to file
        run: echo "${{ env.IMAGE_VERSION }}" > Version


      # ---正式版---
      - name: Build and Push (with latest)
        if: ${{ !contains(env.IMAGE_VERSION, 'beta') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/iptv:latest
            ${{ secrets.DOCKER_USERNAME }}/iptv:${{ env.IMAGE_VERSION }}

      # ---beta---
      - name: Build and Push (beta only)
        if: ${{ contains(env.IMAGE_VERSION, 'beta') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/iptv:${{ env.IMAGE_VERSION }}


      # ---导出执行文件---
      - name: Export binaries for all platforms
        run: |
          TAG="${{ env.IMAGE_VERSION }}"

          if echo "$TAG" | grep -q "beta"; then
            echo "beta 版本，仅导出 amd64"

            docker create --name e1 ${{ secrets.DOCKER_USERNAME }}/iptv:${TAG}
            docker cp e1:/app/iptv ./iptv_amd64
            docker cp e1:/app/license ./license_amd64
            docker rm e1

          else
            echo "正式版本，导出 amd64 arm64 armv7"

            docker create --name e1 ${{ secrets.DOCKER_USERNAME }}/iptv:${TAG}
            docker cp e1:/app/iptv ./iptv_amd64
            docker cp e1:/app/license ./license_amd64
            docker rm e1

            docker create --name e2 ${{ secrets.DOCKER_USERNAME }}/iptv:${TAG}
            docker cp e2:/app/iptv ./iptv_arm64
            docker cp e2:/app/license ./license_arm64
            docker rm e2

            docker create --name e3 ${{ secrets.DOCKER_USERNAME }}/iptv:${TAG}
            docker cp e3:/app/iptv ./iptv_armv7
            docker cp e3:/app/license ./license_armv7
            docker rm e3
          fi

          chmod +x *


      # ---生成 SHA256---
      - name: Generate SHA256
        run: |
          TAG="${{ env.IMAGE_VERSION }}"
          mkdir -p pkg
          mv iptv-* pkg/
          (cd pkg && sha256sum * > SHA256SUMS.txt)
          cp Version pkg/


      # ---创建或更新 Release---
      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.IMAGE_VERSION }}
          name: Release ${{ env.IMAGE_VERSION }}
          prerelease: ${{ contains(env.IMAGE_VERSION, 'beta') }}
          generate_release_notes: true
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # ---上传文件到 release---
      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: pkg/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
